#░█████╗░██╗░░░░░░█████╗░░█████╗░██████╗░██╗████████╗████████╗██╗░░░██╗
#██╔══██╗██║░░░░░██╔══██╗██╔══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗░██╔╝
#███████║██║░░░░░███████║██║░░╚═╝██████╔╝██║░░░██║░░░░░░██║░░░░╚████╔╝░
#██╔══██║██║░░░░░██╔══██║██║░░██╗██╔══██╗██║░░░██║░░░░░░██║░░░░░╚██╔╝░░
#██║░░██║███████╗██║░░██║╚█████╔╝██║░░██║██║░░░██║░░░░░░██║░░░░░░██║░░░
#╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░░░░╚═╝░░░

[font]
  size = 19

  [font.normal]
    family = "Hack Nerd Font"

  [font.bold]
    family = "Hack Nerd Font"

  [font.italic]
    family = "Hack Nerd Font"

# Uncomment the line below to fix lag with Mission Control's animations on macOS
[window]
opacity = 0.9
blur = true

[env]
  TERM = "xterm-256color"

# The definition of color schemes.
import = "./themes/gruvbox_material.toml"

