[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

[colors.selection]
text = '#ebdbb2'
background = '#458588'

[colors.cursor]
text = '#1d2021'
cursor = '#fe8019'

[colors.normal]
black   = '#282828'
red     = '#ec5388'
green   = '#97d66e'
yellow  = '#dbad7b'
blue    = '#cc7633'
magenta = '#c6793c'
cyan    = '#FE8019'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f90'
green   = '#aae086'
yellow  = '#e8c197'
blue    = '#ffc495'
magenta = '#c26d4e'
cyan    = '#a27b4b'
white   = '#ffffff'
