[colors.primary]
background = '#fff8f4'
foreground = '#231a11'

[colors.selection]
text = '#231a11'
background = '#e4dfff'

[colors.cursor]
text = '#fff8f4'
cursor = '#5d5698'

[colors.normal]
black   = '#fff8f4'
red     = '#8c130b'
green   = '#09720d'
yellow  = '#7f7b11'
blue    = '#6954ff'
magenta = '#302681'
cyan    = '#5d5698'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52820'
green   = '#138c18'
yellow  = '#999421'
blue    = '#685fb6'
magenta = '#3f4cff'
cyan    = '#bb59ff'
white   = '#1a1a1a'
