# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#665c54'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#665c54'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'
